services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        MONGO_URL: mongodb://root:example@mongo:27017
        JWT_SECRET: secret
        REDIS_URL: redis://default@redis:6379
    volumes:
      - .:/app
    ports:
      - 5173:5173
  mongo:
    image: mongo
    restart: always
    volumes:
      - db:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  redis:
    image: redis
    restart: always
    volumes:
      - cache:/data
    ports:
      - 6379:6379

volumes:
  db:
  cache: